---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/kontena/kubelet-rubber-stamp

steps:
  - name: test
    image: golang:1.11
    commands:
      - mkdir -p /go/bin
      - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - dep ensure -v -vendor-only
      - ./test.sh

  - name: docker
    image: plugins/docker
    settings:
      registry: quay.io
      secrets: [ docker_username, docker_password ]
      repo: quay.io/kontena/kubelet-rubber-stamp-amd64
      dockerfile: Dockerfile
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker-arm
    image: plugins/docker
    settings:
      registry: quay.io
      secrets: [ docker_username, docker_password ]
      repo: quay.io/kontena/kubelet-rubber-stamp-arm64
      dockerfile: Dockerfile
      build_args:
        - ARCH=arm64
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
