apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubelet-rubber-stamp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubelet-rubber-stamp
  template:
    metadata:
      labels:
        name: kubelet-rubber-stamp
    spec:
      serviceAccountName: kubelet-rubber-stamp
      tolerations:
        - effect: NoSchedule
          operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      containers:
        - name: kubelet-rubber-stamp
          image: quay.io/kontena/kubelet-rubber-stamp-amd64:latest
          args:
            - "--v=2"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["all"]
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubelet-rubber-stamp"
